/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtividadesRouteImport } from './routes/atividades'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConsultaRouteImport } from './routes/consulta'
import { Route as FunilRouteImport } from './routes/funil'
import { Route as ListasRouteImport } from './routes/listas'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as EmpresasIndexRouteImport } from './routes/empresas/index'
import { Route as EmpresasCnpjRouteImport } from './routes/empresas/$cnpj'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesRoute = AtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultaRoute = ConsultaRouteImport.update({
  id: '/consulta',
  path: '/consulta',
  getParentRoute: () => rootRouteImport,
} as any)
const FunilRoute = FunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => rootRouteImport,
} as any)
const ListasRoute = ListasRouteImport.update({
  id: '/listas',
  path: '/listas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasIndexRoute = EmpresasIndexRouteImport.update({
  id: '/empresas/',
  path: '/empresas/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasCnpjRoute = EmpresasCnpjRouteImport.update({
  id: '/empresas/$cnpj',
  path: '/empresas/$cnpj',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/calculadora': typeof CalculadoraRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/consulta': typeof ConsultaRoute
  '/funil': typeof FunilRoute
  '/listas': typeof ListasRoute
  '/relatorios': typeof RelatoriosRoute
  '/empresas/$cnpj': typeof EmpresasCnpjRoute
  '/empresas/': typeof EmpresasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/calculadora': typeof CalculadoraRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/consulta': typeof ConsultaRoute
  '/funil': typeof FunilRoute
  '/listas': typeof ListasRoute
  '/relatorios': typeof RelatoriosRoute
  '/empresas/$cnpj': typeof EmpresasCnpjRoute
  '/empresas': typeof EmpresasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/calculadora': typeof CalculadoraRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/consulta': typeof ConsultaRoute
  '/funil': typeof FunilRoute
  '/listas': typeof ListasRoute
  '/relatorios': typeof RelatoriosRoute
  '/empresas/$cnpj': typeof EmpresasCnpjRoute
  '/empresas/': typeof EmpresasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atividades'
    | '/calculadora'
    | '/configuracoes'
    | '/consulta'
    | '/funil'
    | '/listas'
    | '/relatorios'
    | '/empresas/$cnpj'
    | '/empresas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atividades'
    | '/calculadora'
    | '/configuracoes'
    | '/consulta'
    | '/funil'
    | '/listas'
    | '/relatorios'
    | '/empresas/$cnpj'
    | '/empresas'
  id:
    | '__root__'
    | '/'
    | '/atividades'
    | '/calculadora'
    | '/configuracoes'
    | '/consulta'
    | '/funil'
    | '/listas'
    | '/relatorios'
    | '/empresas/$cnpj'
    | '/empresas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtividadesRoute: typeof AtividadesRoute
  CalculadoraRoute: typeof CalculadoraRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConsultaRoute: typeof ConsultaRoute
  FunilRoute: typeof FunilRoute
  ListasRoute: typeof ListasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  EmpresasCnpjRoute: typeof EmpresasCnpjRoute
  EmpresasIndexRoute: typeof EmpresasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades': {
      id: '/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulta': {
      id: '/consulta'
      path: '/consulta'
      fullPath: '/consulta'
      preLoaderRoute: typeof ConsultaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funil': {
      id: '/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof FunilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listas': {
      id: '/listas'
      path: '/listas'
      fullPath: '/listas'
      preLoaderRoute: typeof ListasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas/': {
      id: '/empresas/'
      path: '/empresas'
      fullPath: '/empresas/'
      preLoaderRoute: typeof EmpresasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas/$cnpj': {
      id: '/empresas/$cnpj'
      path: '/empresas/$cnpj'
      fullPath: '/empresas/$cnpj'
      preLoaderRoute: typeof EmpresasCnpjRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtividadesRoute: AtividadesRoute,
  CalculadoraRoute: CalculadoraRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConsultaRoute: ConsultaRoute,
  FunilRoute: FunilRoute,
  ListasRoute: ListasRoute,
  RelatoriosRoute: RelatoriosRoute,
  EmpresasCnpjRoute: EmpresasCnpjRoute,
  EmpresasIndexRoute: EmpresasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
