DROP VIEW public.v_carteira;
CREATE VIEW public.v_carteira AS
SELECT co.cnpj,
    co.razao_social,
    co.nome_fantasia,
    co.tipo_unidade,
    co.situacao,
    co.natureza_juridica,
    co.logradouro,
    co.numero,
    co.complemento,
    co.bairro,
    co.cep,
    co.cidade,
    co.uf,
    co.cnae_codigo,
    co.cnae_descricao,
    co.setores,
    co.porte_estimado,
    co.enquadramento_porte,
    co.faturamento_presumido,
    co.qtd_funcionarios_estimada,
    co.capital_social,
    co.data_abertura,
    co.simples_optante,
    co.simples_desde,
    co.mei_optante,
    co.mei_desde,
    co.melhor_telefone,
    co.telefones,
    co.melhor_site,
    co.sites,
    co.email_receita,
    co.emails,
    co.contatos,
    co.decisores,
    co.link_detalhe,
    co.raw,
    co.fonte_principal,
    co.fontes,
    co.synced_at,
    co.enriquecido_em,
    ct.id AS carteira_id,
    ct.unit_id,
    ct.status,
    ct.prospectar,
    ct.notas,
    ct.tags,
    ct.list_id,
    ct.product_id,
    ct.owner_id,
    ct.owner_desde,
    ct.created_at,
    ct.updated_at
   FROM public.companies co
     JOIN public.carteira ct ON ct.cnpj = co.cnpj;